import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  WidthType,
  AlignmentType,
  BorderStyle,
  HeadingLevel,
} from 'docx';
import { CareerReport, ResumeRecord } from '@/types';

/**
 * Palette constants for DOCX styling matching Light Green theme
 */
const COLOR_PRIMARY_GREEN = '16A34A'; // Brand Green
const COLOR_DARK_GREEN = '166534';    // Heading Green
const COLOR_MINT = 'ECFDF5';          // Table header background
const COLOR_LIGHT_BG = 'F0FDF4';      // Zebra striping
const COLOR_BORDER = 'DCE9DF';        // Border green
const COLOR_TEXT = '17251B';          // Primary text
const COLOR_MUTED = '526157';         // Secondary text

/**
 * Generate a complete, professionally formatted Word Document (.docx)
 */
export async function createDocxDocument(report: CareerReport): Promise<Document> {
  const borderDefinition = {
    top: { style: BorderStyle.SINGLE, size: 1, color: COLOR_BORDER },
    bottom: { style: BorderStyle.SINGLE, size: 1, color: COLOR_BORDER },
    left: { style: BorderStyle.SINGLE, size: 1, color: COLOR_BORDER },
    right: { style: BorderStyle.SINGLE, size: 1, color: COLOR_BORDER },
  };

  // Helper for Section Titles
  const createSectionHeader = (number: string, title: string) =>
    new Paragraph({
      heading: HeadingLevel.HEADING_2,
      spacing: { before: 360, after: 140 },
      children: [
        new TextRun({
          text: `${number}. ${title.toUpperCase()}`,
          bold: true,
          size: 26,
          color: COLOR_DARK_GREEN,
          font: 'Arial',
        }),
      ],
    });

  // 1. Skill Profile Table Rows
  const skillTableRows: TableRow[] = [
    new TableRow({
      tableHeader: true,
      children: [
        createHeaderCell('Skill Name', 25),
        createHeaderCell('Category', 20),
        createHeaderCell('Estimated Score', 20),
        createHeaderCell('Evidence / Status', 35),
      ],
    }),
  ];

  report.skills.slice(0, 15).forEach((skill, idx) => {
    const isEven = idx % 2 === 0;
    skillTableRows.push(
      new TableRow({
        children: [
          createDataCell(skill.name, 25, isEven, true),
          createDataCell(skill.category.toUpperCase(), 20, isEven),
          createDataCell(`${skill.score}%`, 20, isEven),
          createDataCell(skill.evidenceSnippet || 'Detected from resume evidence', 35, isEven),
        ],
      })
    );
  });

  // 2. Skill Gap Table Rows
  const gapTableRows: TableRow[] = [
    new TableRow({
      tableHeader: true,
      children: [
        createHeaderCell('Competency', 25),
        createHeaderCell('Current vs Target', 20),
        createHeaderCell('Gap Status', 20),
        createHeaderCell('Recommended Action', 35),
      ],
    }),
  ];

  report.skillGaps.forEach((gap, idx) => {
    const isEven = idx % 2 === 0;
    gapTableRows.push(
      new TableRow({
        children: [
          createDataCell(gap.skill, 25, isEven, true),
          createDataCell(`${gap.currentScore}% / ${gap.targetScore}%`, 20, isEven),
          createDataCell(gap.status, 20, isEven, false, gap.status === 'Missing' ? 'DC2626' : gap.status === 'Acquired' ? COLOR_PRIMARY_GREEN : 'D97706'),
          createDataCell(gap.recommendedAction || gap.gapReason, 35, isEven),
        ],
      })
    );
  });

  // 3. Opportunity Table Rows
  const opportunityTableRows: TableRow[] = [
    new TableRow({
      tableHeader: true,
      children: [
        createHeaderCell('Role & Company', 30),
        createHeaderCell('Match %', 15),
        createHeaderCell('Matched Skills', 25),
        createHeaderCell('Employer Rationale', 30),
      ],
    }),
  ];

  report.opportunities.slice(0, 6).forEach((match, idx) => {
    const isEven = idx % 2 === 0;
    opportunityTableRows.push(
      new TableRow({
        children: [
          createDataCell(`${match.opportunity.title} — ${match.opportunity.company}`, 30, isEven, true),
          createDataCell(`${match.matchScore}%`, 15, isEven, true, COLOR_PRIMARY_GREEN),
          createDataCell(match.matchedSkills.slice(0, 4).join(', ') || 'Core Competencies', 25, isEven),
          createDataCell(match.whyMatched[0] || match.recommendedAction, 30, isEven),
        ],
      })
    );
  });

  const doc = new Document({
    creator: 'SkillBridge AI Platform',
    title: `Career Intelligence Report - ${report.candidateInfo.name}`,
    description: `Automated Career Intelligence Report for ${report.candidateInfo.name} generated by SkillBridge AI (SIH26044).`,
    sections: [
      {
        properties: {
          page: {
            margin: { top: 1200, bottom: 1200, left: 1200, right: 1200 },
          },
        },
        children: [
          // Platform Header
          new Paragraph({
            alignment: AlignmentType.LEFT,
            children: [
              new TextRun({
                text: 'SKILLBRIDGE AI',
                bold: true,
                size: 32,
                color: COLOR_PRIMARY_GREEN,
                font: 'Arial',
              }),
            ],
          }),
          new Paragraph({
            alignment: AlignmentType.LEFT,
            spacing: { after: 240 },
            children: [
              new TextRun({
                text: 'Academia × Industry Intelligence Platform • SIH 2026 Prototype (SIH26044)',
                italics: true,
                size: 18,
                color: COLOR_MUTED,
                font: 'Arial',
              }),
            ],
          }),

          // Report Title Card
          new Paragraph({
            spacing: { before: 180, after: 80 },
            children: [
              new TextRun({
                text: 'CAREER INTELLIGENCE & SKILL AUDIT REPORT',
                bold: true,
                size: 28,
                color: COLOR_DARK_GREEN,
                font: 'Arial',
              }),
            ],
          }),
          new Paragraph({
            spacing: { after: 280 },
            children: [
              new TextRun({ text: 'Candidate: ', bold: true, size: 20, color: COLOR_TEXT, font: 'Arial' }),
              new TextRun({ text: `${report.candidateInfo.name}  |  `, size: 20, color: COLOR_TEXT, font: 'Arial' }),
              new TextRun({ text: 'Target Role: ', bold: true, size: 20, color: COLOR_TEXT, font: 'Arial' }),
              new TextRun({ text: `${report.targetRole}  |  `, size: 20, color: COLOR_TEXT, font: 'Arial' }),
              new TextRun({ text: 'Readiness Score: ', bold: true, size: 20, color: COLOR_PRIMARY_GREEN, font: 'Arial' }),
              new TextRun({ text: `${report.readinessScore}% (Model-Based)  |  `, bold: true, size: 20, color: COLOR_PRIMARY_GREEN, font: 'Arial' }),
              new TextRun({ text: 'Date: ', bold: true, size: 20, color: COLOR_MUTED, font: 'Arial' }),
              new TextRun({ text: `${report.generatedAt}`, size: 20, color: COLOR_MUTED, font: 'Arial' }),
            ],
          }),

          // Section 1: Executive Summary
          createSectionHeader('1', 'Executive Profile & Academic Background'),
          new Paragraph({
            spacing: { after: 120 },
            children: [
              new TextRun({ text: '• Institution / College: ', bold: true, size: 20, color: COLOR_TEXT, font: 'Arial' }),
              new TextRun({ text: `${report.candidateInfo.college || 'Engineering College'}`, size: 20, color: COLOR_TEXT, font: 'Arial' }),
            ],
          }),
          new Paragraph({
            spacing: { after: 120 },
            children: [
              new TextRun({ text: '• Degree / Program: ', bold: true, size: 20, color: COLOR_TEXT, font: 'Arial' }),
              new TextRun({ text: `${report.candidateInfo.degree || 'Bachelor of Technology'}`, size: 20, color: COLOR_TEXT, font: 'Arial' }),
            ],
          }),
          new Paragraph({
            spacing: { after: 120 },
            children: [
              new TextRun({ text: '• Email / Contact: ', bold: true, size: 20, color: COLOR_TEXT, font: 'Arial' }),
              new TextRun({ text: `${report.candidateInfo.email || 'N/A'} | ${report.candidateInfo.phone || 'N/A'}`, size: 20, color: COLOR_TEXT, font: 'Arial' }),
            ],
          }),
          new Paragraph({
            spacing: { after: 240 },
            children: [
              new TextRun({ text: '• Analyzed Document: ', bold: true, size: 20, color: COLOR_TEXT, font: 'Arial' }),
              new TextRun({ text: `${report.resumeMeta.fileName} (${report.resumeMeta.fileSize})`, size: 20, color: COLOR_MUTED, font: 'Arial' }),
            ],
          }),

          // Section 2: Technical Skill Profile
          createSectionHeader('2', 'Extracted Technical Competency Profile'),
          new Paragraph({
            spacing: { after: 140 },
            children: [
              new TextRun({
                text: 'The following skills were extracted from the candidate resume using SkillBridge 150+ technology taxonomy and mapped to evidence snippets. Scores are marked as "Estimated from resume evidence" pending proctored verification.',
                size: 18,
                color: COLOR_MUTED,
                font: 'Arial',
              }),
            ],
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: skillTableRows,
          }),

          // Section 3: Skill Gap Analysis
          createSectionHeader('3', `Skill Gap Diagnostics — Benchmark: ${report.targetRole}`),
          new Paragraph({
            spacing: { after: 140 },
            children: [
              new TextRun({
                text: `Skill gap diagnostic evaluating current competencies against standard industry hiring requirements for ${report.targetRole}.`,
                size: 18,
                color: COLOR_MUTED,
                font: 'Arial',
              }),
            ],
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: gapTableRows,
          }),

          // Section 4: 5-Factor Career Readiness Breakdown
          createSectionHeader('4', 'Deterministic 5-Factor Career Readiness Breakdown'),
          new Paragraph({
            spacing: { after: 100 },
            children: [
              new TextRun({ text: `Overall Career Readiness: ${report.readinessScore}%`, bold: true, size: 22, color: COLOR_PRIMARY_GREEN, font: 'Arial' }),
            ],
          }),
          new Paragraph({
            spacing: { after: 60 },
            children: [
              new TextRun({ text: `• Technical Skills Factor: `, bold: true, size: 18, color: COLOR_TEXT, font: 'Arial' }),
              new TextRun({ text: `${report.scoreBreakdown.technicalSkills} / 50 points`, size: 18, color: COLOR_TEXT, font: 'Arial' }),
            ],
          }),
          new Paragraph({
            spacing: { after: 60 },
            children: [
              new TextRun({ text: `• Practical Projects Relevance: `, bold: true, size: 18, color: COLOR_TEXT, font: 'Arial' }),
              new TextRun({ text: `${report.scoreBreakdown.projects} / 15 points`, size: 18, color: COLOR_TEXT, font: 'Arial' }),
            ],
          }),
          new Paragraph({
            spacing: { after: 60 },
            children: [
              new TextRun({ text: `• Assessment Performance: `, bold: true, size: 18, color: COLOR_TEXT, font: 'Arial' }),
              new TextRun({ text: `${report.scoreBreakdown.assessment} / 15 points`, size: 18, color: COLOR_TEXT, font: 'Arial' }),
            ],
          }),
          new Paragraph({
            spacing: { after: 60 },
            children: [
              new TextRun({ text: `• Industry Experience: `, bold: true, size: 18, color: COLOR_TEXT, font: 'Arial' }),
              new TextRun({ text: `${report.scoreBreakdown.experience} / 10 points`, size: 18, color: COLOR_TEXT, font: 'Arial' }),
            ],
          }),
          new Paragraph({
            spacing: { after: 240 },
            children: [
              new TextRun({ text: `• Verified Certifications: `, bold: true, size: 18, color: COLOR_TEXT, font: 'Arial' }),
              new TextRun({ text: `${report.scoreBreakdown.certifications} / 10 points`, size: 18, color: COLOR_TEXT, font: 'Arial' }),
            ],
          }),

          // Section 5: Recommended Opportunities
          createSectionHeader('5', 'Explainable Industry Opportunity Matching'),
          new Paragraph({
            spacing: { after: 140 },
            children: [
              new TextRun({
                text: 'Matched opportunities calculated against active SIH partner requisitions with transparent matching criteria.',
                size: 18,
                color: COLOR_MUTED,
                font: 'Arial',
              }),
            ],
          }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: opportunityTableRows,
          }),

          // Section 6: Resume Insights & Recommendations
          createSectionHeader('6', 'AI Resume Audit: Strengths, Deficits & Recommendations'),
          new Paragraph({
            spacing: { after: 60 },
            children: [new TextRun({ text: 'Key Strengths:', bold: true, size: 20, color: COLOR_DARK_GREEN, font: 'Arial' })],
          }),
          ...report.strengths.map(
            (s) =>
              new Paragraph({
                spacing: { after: 60 },
                children: [new TextRun({ text: `✓ ${s}`, size: 18, color: COLOR_TEXT, font: 'Arial' })],
              })
          ),
          new Paragraph({
            spacing: { before: 120, after: 60 },
            children: [new TextRun({ text: 'Identified Competency Deficits:', bold: true, size: 20, color: 'DC2626', font: 'Arial' })],
          }),
          ...report.weaknesses.map(
            (w) =>
              new Paragraph({
                spacing: { after: 60 },
                children: [new TextRun({ text: `△ ${w}`, size: 18, color: COLOR_TEXT, font: 'Arial' })],
              })
          ),
          new Paragraph({
            spacing: { before: 120, after: 60 },
            children: [new TextRun({ text: 'Curated Recommendations:', bold: true, size: 20, color: COLOR_TEXT, font: 'Arial' })],
          }),
          ...report.recommendations.map(
            (r) =>
              new Paragraph({
                spacing: { after: 60 },
                children: [new TextRun({ text: `• ${r}`, size: 18, color: COLOR_TEXT, font: 'Arial' })],
              })
          ),

          // Section 7: Action Plan
          createSectionHeader('7', 'Recommended Upskilling Action Plan'),
          ...report.actionPlan.map(
            (step, i) =>
              new Paragraph({
                spacing: { after: 80 },
                children: [
                  new TextRun({ text: `Step ${i + 1}: `, bold: true, size: 18, color: COLOR_PRIMARY_GREEN, font: 'Arial' }),
                  new TextRun({ text: step, size: 18, color: COLOR_TEXT, font: 'Arial' }),
                ],
              })
          ),

          // Footer
          new Paragraph({
            spacing: { before: 400 },
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text: 'SkillBridge AI • Ministry of Ayush / All India Institute of Ayurveda • Smart India Hackathon 2026',
                size: 16,
                color: COLOR_MUTED,
                italics: true,
                font: 'Arial',
              }),
            ],
          }),
        ],
      },
    ],
  });

  return doc;
}

// Table helper functions
function createHeaderCell(text: string, widthPercent: number): TableCell {
  return new TableCell({
    width: { size: widthPercent, type: WidthType.PERCENTAGE },
    shading: { fill: COLOR_MINT },
    children: [
      new Paragraph({
        alignment: AlignmentType.LEFT,
        children: [new TextRun({ text, bold: true, size: 18, color: COLOR_DARK_GREEN, font: 'Arial' })],
      }),
    ],
  });
}

function createDataCell(
  text: string,
  widthPercent: number,
  isEven: boolean,
  bold = false,
  textColor = COLOR_TEXT
): TableCell {
  return new TableCell({
    width: { size: widthPercent, type: WidthType.PERCENTAGE },
    shading: { fill: isEven ? 'FFFFFF' : COLOR_LIGHT_BG },
    children: [
      new Paragraph({
        alignment: AlignmentType.LEFT,
        children: [new TextRun({ text, bold, size: 16, color: textColor, font: 'Arial' })],
      }),
    ],
  });
}

/**
 * Generate binary Blob or Buffer for DOCX
 */
export async function generateDocxBlob(report: CareerReport): Promise<Blob> {
  const doc = await createDocxDocument(report);
  return await Packer.toBlob(doc);
}

/**
 * Generate formatted JSON report string
 */
export function generateJsonReport(report: CareerReport): string {
  return JSON.stringify(
    {
      reportTitle: 'SkillBridge AI Career Intelligence Report',
      platform: 'SkillBridge AI — Academia × Industry Intelligence Platform',
      hackathonProblem: 'SIH26044 (Ministry of Ayush / All India Institute of Ayurveda)',
      reportVersion: `v${report.version}.0`,
      generatedAt: report.generatedAt,
      candidate: {
        name: report.candidateInfo.name,
        email: report.candidateInfo.email,
        phone: report.candidateInfo.phone,
        education: report.candidateInfo.education,
        degree: report.candidateInfo.degree,
        college: report.candidateInfo.college,
        experienceYears: report.candidateInfo.experienceYears,
      },
      resumeSource: {
        fileName: report.resumeMeta.fileName,
        fileSize: report.resumeMeta.fileSize,
        fileType: report.resumeMeta.fileType,
        uploadedAt: report.resumeMeta.uploadedAt,
      },
      targetRole: report.targetRole,
      readiness: {
        score: report.readinessScore,
        modelType: 'Prototype readiness model (Deterministic 5-Factor)',
        scoreBreakdown: report.scoreBreakdown,
      },
      skills: report.skills,
      softSkills: report.softSkills,
      tools: report.tools,
      skillGaps: {
        criticalGaps: report.criticalGaps,
        moderateGaps: report.moderateGaps,
        strongSkills: report.strongSkills,
        allGaps: report.skillGaps,
      },
      recommendedOpportunities: report.opportunities.map((o) => ({
        title: o.opportunity.title,
        company: o.opportunity.company,
        location: o.opportunity.location,
        type: o.opportunity.type,
        matchScore: o.matchScore,
        matchedSkills: o.matchedSkills,
        missingSkills: o.missingSkills,
        whyMatched: o.whyMatched,
        recommendedAction: o.recommendedAction,
      })),
      roadmap: report.roadmap,
      auditInsights: {
        strengths: report.strengths,
        weaknesses: report.weaknesses,
        recommendations: report.recommendations,
        actionPlan: report.actionPlan,
      },
    },
    null,
    2
  );
}

/**
 * Browser file download helpers
 */
export function downloadBlob(blob: Blob, filename: string): void {
  if (typeof window === 'undefined') return;
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = sanitizeFilename(filename);
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
  URL.revokeObjectURL(url);
}

export function downloadTextFile(content: string, filename: string, mimeType = 'application/json'): void {
  const blob = new Blob([content], { type: mimeType });
  downloadBlob(blob, filename);
}

export async function downloadDocxReport(report: CareerReport): Promise<void> {
  const blob = await generateDocxBlob(report);
  const cleanName = report.candidateInfo.name.replace(/\s+/g, '_') || 'Candidate';
  const dateStr = new Date().toISOString().split('T')[0];
  const filename = `SkillBridge_Career_Report_${cleanName}_${dateStr}.docx`;
  downloadBlob(blob, filename);
}

export function downloadJsonReport(report: CareerReport): void {
  const jsonContent = generateJsonReport(report);
  const cleanName = report.candidateInfo.name.replace(/\s+/g, '_') || 'Candidate';
  const dateStr = new Date().toISOString().split('T')[0];
  const filename = `SkillBridge_Career_Report_${cleanName}_${dateStr}.json`;
  downloadTextFile(jsonContent, filename, 'application/json');
}

export function downloadOriginalResumeFile(record: ResumeRecord): void {
  if (!record.fileDataUrl) {
    // If raw Data URL is not available, export the raw text as a text file
    downloadTextFile(
      record.rawText || 'Resume file content',
      record.fileName.endsWith('.txt') ? record.fileName : `${record.fileName}.txt`,
      'text/plain'
    );
    return;
  }

  // Download from stored Data URL
  const anchor = document.createElement('a');
  anchor.href = record.fileDataUrl;
  anchor.download = sanitizeFilename(record.fileName || 'Uploaded_Resume.pdf');
  document.body.appendChild(anchor);
  anchor.click();
  document.body.removeChild(anchor);
}

function sanitizeFilename(filename: string): string {
  return filename.replace(/[^a-zA-Z0-9._-]/g, '_');
}
